"use client";

import {
	agoric,
	agoricAssetList,
	akash,
	akashAssetList,
	axelar,
	axelarAssetList,
	bostrom,
	bostromAssetList,
	celestia,
	celestiaAssetList,
	chihuahua,
	chihuahuaAssetList,
	cosmoshub,
	cosmoshubAssetList,
	dydx,
	dydxAssetList,
	dymension,
	dymensionAssetList,
	evmos,
	evmosAssetList,
	gitopia,
	gitopiaAssetList,
	gravitybridge,
	gravitybridgeAssetList,
	injective,
	injectiveAssetList,
	irisnet,
	irisnetAssetList,
	juno,
	junoAssetList,
	kava,
	kavaAssetList,
	kyve,
	kyveAssetList,
	likecoin,
	likecoinAssetList,
	mars,
	marsAssetList,
	neutron,
	neutronAssetList,
	noble,
	nobleAssetList,
	omniflixhub,
	omniflixhubAssetList,
	osmosis,
	osmosisAssetList,
	passage,
	passageAssetList,
	persistence,
	persistenceAssetList,
	pryzm,
	pryzmAssetList,
	quasar,
	quasarAssetList,
	quicksilver,
	quicksilverAssetList,
	regen,
	regenAssetList,
	saga,
	sagaAssetList,
	secretnetwork,
	secretnetworkAssetList,
	seda,
	sedaAssetList,
	sentinel,
	sentinelAssetList,
	shentu,
	shentuAssetList,
	sifchain,
	sifchainAssetList,
	sommelier,
	sommelierAssetList,
	stargaze,
	stargazeAssetList,
	stride,
	strideAssetList,
	terra,
	terraAssetList,
	xpla,
	xplaAssetList,
	zetachain,
	zetachainAssetList,
} from "@nabla-studio/chain-registry";
import { QuirksConfig, QuirksNextProvider } from "@quirks/react";
import type { Config } from "@quirks/store";
import {
	cosmostationExtension,
	keplrExtension,
	leapExtension,
} from "@quirks/wallets";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { PropsWithChildren } from "react";

const config: Config = {
	wallets: [keplrExtension, leapExtension, cosmostationExtension],
	chains: [
		cosmoshub,
		osmosis,
		agoric,
		akash,
		axelar,
		bostrom,
		celestia,
		chihuahua,
		dydx,
		dymension,
		evmos,
		gitopia,
		gravitybridge,
		injective,
		irisnet,
		juno,
		kava,
		kyve,
		likecoin,
		mars,
		neutron,
		noble,
		omniflixhub,
		passage,
		persistence,
		pryzm,
		quasar,
		quicksilver,
		regen,
		saga,
		secretnetwork,
		seda,
		sentinel,
		shentu,
		sifchain,
		sommelier,
		stargaze,
		stride,
		terra,
		xpla,
		zetachain,
	],
	assetsLists: [
		cosmoshubAssetList,
		osmosisAssetList,
		agoricAssetList,
		akashAssetList,
		axelarAssetList,
		bostromAssetList,
		celestiaAssetList,
		chihuahuaAssetList,
		dydxAssetList,
		dymensionAssetList,
		evmosAssetList,
		gitopiaAssetList,
		gravitybridgeAssetList,
		injectiveAssetList,
		irisnetAssetList,
		junoAssetList,
		kavaAssetList,
		kyveAssetList,
		likecoinAssetList,
		marsAssetList,
		neutronAssetList,
		nobleAssetList,
		omniflixhubAssetList,
		passageAssetList,
		persistenceAssetList,
		pryzmAssetList,
		quasarAssetList,
		quicksilverAssetList,
		regenAssetList,
		sagaAssetList,
		secretnetworkAssetList,
		sedaAssetList,
		sentinelAssetList,
		shentuAssetList,
		sifchainAssetList,
		sommelierAssetList,
		stargazeAssetList,
		strideAssetList,
		terraAssetList,
		xplaAssetList,
		zetachainAssetList,
	],
	autoSuggestions: false,
};

export const Provider = ({ children }: PropsWithChildren<unknown>) => {
	const qc = new QueryClient();
	return (
		<QuirksNextProvider>
			<QueryClientProvider client={qc}>
				<QuirksConfig config={config}>{children}</QuirksConfig>
			</QueryClientProvider>
		</QuirksNextProvider>
	);
};
